# Generated by Django 4.0.4 on 2022-10-04 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Unidad de medida')),
                ('type', models.CharField(choices=[('Masa', 'Masa'), ('Volumen', 'Volumen')], default='Masa', max_length=30, verbose_name='Tipo de medida')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='name_unitMeasurement',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Tipo de medida'),
        ),
        migrations.AddField(
            model_name='product',
            name='unitMeasurement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.unit', verbose_name='Unidad de Medida'),
        ),
    ]
