# Generated by Django 4.0.3 on 2022-09-26 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_unit_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
