# Generated by Django 4.0.4 on 2022-09-24 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_alter_sale_user'),
        ('management', '0003_user_cambiarcontra'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CambiarContra',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
