# Generated by Django 4.0.3 on 2022-09-30 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_backup_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unitMeasurement',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
