# Generated by Django 4.0.3 on 2022-09-30 15:02

from django.db import migrations, models
import management.models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_remove_product_unitmeasurement_delete_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='file',
            field=models.FileField(upload_to='media', validators=[management.models.validate_file_extension], verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='name',
            field=models.CharField(blank=True, default='Copia de Seguridad', max_length=200, verbose_name='Nombre'),
        ),
    ]
