# Generated by Django 4.0.4 on 2022-09-29 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_remove_sale_userregister_sale_user'),
        ('management', '0005_userregister'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRegister',
        ),
    ]
