# Generated by Django 4.0.4 on 2022-10-03 09:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Compra')),
                ('payment', models.CharField(choices=[('Datáfono', 'Datáfono'), ('Efectivo', 'Efectivo'), ('Transacción', 'Transacción')], default='Efectivo', max_length=11, verbose_name='Método de Pago')),
                ('finalPrice', models.IntegerField(blank=True, default=0)),
                ('observation', models.CharField(blank=True, choices=[('Devolución', 'Devolución'), ('Cambio', 'Cambio'), ('Otro', 'Otro')], default=' ', max_length=15, null=True, verbose_name='Observaciones')),
                ('status', models.CharField(choices=[('Abierta', 'Abierta'), ('Cerrada', 'Cerrada'), ('Pendiente', 'Pendiente'), ('Anulada', 'Anulada')], default='Abierta', max_length=10, verbose_name='Estado')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.provider', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, verbose_name='Fecha de Venta')),
                ('client', models.CharField(blank=True, default='Cliente local', max_length=50, verbose_name='Cliente')),
                ('nDocument', models.CharField(blank=True, default=1234567890, max_length=20, verbose_name='Número de Documento / NIT')),
                ('address', models.CharField(blank=True, default='Local', max_length=254, verbose_name='Dirección')),
                ('typeSale', models.CharField(choices=[('store', 'Local'), ('Domicilio', 'Domicilio')], default='store', max_length=9, verbose_name='Tipo de Venta')),
                ('finalPrice', models.IntegerField(blank=True, default=0)),
                ('payment', models.CharField(choices=[('Datáfono', 'Datáfono'), ('Efectivo', 'Efectivo'), ('Transacción', 'Transacción')], default='Efectivo', max_length=11, verbose_name='Método de Pago')),
                ('observation', models.CharField(blank=True, choices=[('Devolución', 'Devolución'), ('Cambio', 'Cambio'), ('Otro', 'Otro')], default=' ', max_length=15, null=True, verbose_name='Observaciones')),
                ('status', models.CharField(choices=[('Abierta', 'Abierta'), ('Cerrada', 'Cerrada'), ('Pendiente', 'Pendiente'), ('Anulada', 'Anulada')], default='Abierta', max_length=10, verbose_name='Estado')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.user', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
            },
        ),
        migrations.CreateModel(
            name='DetailSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad')),
                ('total', models.IntegerField(blank=True, default=0)),
                ('status', models.CharField(choices=[('Abierta', 'Abierta'), ('Cerrada', 'Cerrada'), ('Pendiente', 'Pendiente'), ('Anulada', 'Anulada')], default='Abierta', max_length=10, verbose_name='Estado')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.product', verbose_name='Producto')),
                ('sale', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.sale', verbose_name='Id Venta')),
            ],
            options={
                'verbose_name': 'Detalle de venta',
                'verbose_name_plural': 'Detalle de ventas',
            },
        ),
        migrations.CreateModel(
            name='DetailBuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad')),
                ('total', models.IntegerField(blank=True, default=0)),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('buy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.buy', verbose_name='Id Compra')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Detalle de compra',
                'verbose_name_plural': 'Detalle de compras',
            },
        ),
    ]
