# Generated by Django 4.0.3 on 2022-09-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buy',
            old_name='provider',
            new_name='user',
        ),
        migrations.AddField(
            model_name='buy',
            name='observation',
            field=models.CharField(choices=[('Devolución', 'Devolución'), ('Cambio', 'Cambio'), ('Otro', 'Otro')], default='Devolución', max_length=15, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='sale',
            name='observation',
            field=models.CharField(choices=[('Devolución', 'Devolución'), ('Cambio', 'Cambio'), ('Otro', 'Otro')], default='Devolución', max_length=15, verbose_name='Observaciones'),
        ),
    ]
