# Generated by Django 4.0.3 on 2022-10-01 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_remove_sale_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='payment',
            field=models.CharField(choices=[('Datáfono', 'Datáfono'), ('Efectivo', 'Efectivo'), ('Transacción', 'Transacción')], default='Efectivo', max_length=11, verbose_name='Método de Pago'),
        ),
        migrations.AlterField(
            model_name='buy',
            name='status',
            field=models.CharField(choices=[('Abierta', 'Abierta'), ('Cerrada', 'Cerrada'), ('Pendiente', 'Pendiente'), ('Anulada', 'Anulada')], default='Abierta', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='detailsale',
            name='status',
            field=models.CharField(choices=[('Abierta', 'Abierta'), ('Cerrada', 'Cerrada'), ('Pendiente', 'Pendiente'), ('Anulada', 'Anulada')], default='Abierta', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment',
            field=models.CharField(choices=[('Datáfono', 'Datáfono'), ('Efectivo', 'Efectivo'), ('Transacción', 'Transacción')], default='Efectivo', max_length=11, verbose_name='Método de Pago'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('Abierta', 'Abierta'), ('Cerrada', 'Cerrada'), ('Pendiente', 'Pendiente'), ('Anulada', 'Anulada')], default='Abierta', max_length=10, verbose_name='Estado'),
        ),
    ]
