# Generated by Django 4.0.4 on 2022-09-24 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_userregister'),
        ('invoice', '0003_alter_sale_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.userregister', verbose_name='Empleado'),
        ),
    ]
