# Generated by Django 4.0.4 on 2022-09-29 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_alter_sale_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='user',
            new_name='userRegister',
        ),
    ]
