# Generated by Django 4.0.3 on 2022-09-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_alter_buy_observation_alter_sale_observation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='observation',
            field=models.CharField(blank=True, choices=[('Devolución', 'Devolución'), ('Cambio', 'Cambio'), ('Otro', 'Otro')], max_length=15, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='observation',
            field=models.CharField(blank=True, choices=[('Devolución', 'Devolución'), ('Cambio', 'Cambio'), ('Otro', 'Otro')], max_length=15, null=True, verbose_name='Observaciones'),
        ),
    ]
