# Generated by Django 4.0.4 on 2022-09-29 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('invoice', '0005_rename_user_sale_userregister'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='userRegister',
        ),
        migrations.AddField(
            model_name='sale',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.user', verbose_name='Empleado'),
        ),
    ]
