# Generated by Django 4.0.3 on 2022-09-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_alter_sale_observation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='payment',
            field=models.CharField(choices=[('Datáfono', 'Datáfono'), ('Efectivo', 'Efectivo'), ('Transacción', 'Transaccion')], default='Efectivo', max_length=11, verbose_name='Método de Pago'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment',
            field=models.CharField(choices=[('Datáfono', 'Datáfono'), ('Efectivo', 'Efectivo'), ('Transacción', 'Transaccion')], default='Efectivo', max_length=11, verbose_name='Método de Pago'),
        ),
    ]
