# Generated by Django 4.0.4 on 2022-10-03 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_rename_user_sale_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='username',
        ),
    ]
