# Generated by Django 4.0.3 on 2022-09-30 12:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_alter_buy_payment_alter_sale_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailbuy',
            name='amount',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='detailsale',
            name='amount',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad'),
        ),
    ]
